version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  build:
    steps:
      -run:
          name: Build Image
          command: |
            docker build --tag nikkinicholasromero/email-service-image:0.1 .
      - run:
          name: Docker Login
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: Push Image
          command: |
            docker push nikkinicholasromero/email-service-image:0.1
workflows:
  maven_test_:
    jobs:
      - maven/test/build
